-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, CONCAT_WS(' ', B.CITY, B.STREET_ADDRESS1, B.STREET_ADDRESS2) AS CITY, 
CONCAT_WS('-', LEFT(TLNO, 3), MID(TLNO, 4, 4), RIGHT(TLNO, 4)) AS TLNO FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_USER AS B ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY B.USER_ID DESC;